pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
             when {
                branch 'master'
            }
            steps {
                script {
                    docker image build -t asadis7171/Jenkins-Dev:v1 .
                    docker login
                    docker push asadis7171/Jenkins-Dev:v1

                    

                    // Build Docker image
                    dockerImage = docker.build("your-docker-hub-username/your-image-name:${dockerTag}")

                    // Push Docker image to respective Docker Hub registry
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials-id') {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
