pipeline {
    agent any

    stages {
        stage('Build Docker Dev Image') {
            when {
                branch 'dev'
            }
            steps {
                script {
                    def app = docker.build("asadis7171/dev:latest")
                    docker.withRegistry('https://registry.hub.docker.com/asadis7171/dev', 'docker-cred') {
                        app.push()
                    }
                }
            }
        }

        stage('Build Docker QA Image') {
            when {
                branch 'qa'
            }
            steps {
                script {
                    def app = docker.build("asadis7171/qa:latest")
                    docker.withRegistry('https://registry.hub.docker.com/asadis7171/dev', 'docker-cred') {
                        app.push()
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Deleting Project now !! '
            deleteDir()
        }
    }
}



